#!/usr/bin/env ruby
#
# ./bb - a CLI for boson_bundler
#
# Author:: Ryan Kraay (<r.kraay@kurses.com>)
# Copyright:: Copyright (c) 2011 Ryan Kraay
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'rubygems'
require 'boson'

# Monkey-patch the local repo, so it's relative to this file
module Boson
    def local_repo
        # Repo.new will automatically append ./commands to all the directories
        Repo.new(File.expand_path("../..", __FILE__))
    end
end

require 'boson/runners/bin_runner'

Boson::BinRunner.start
